### ISSUE TITLE
No module named 'attention'

### ISSUE THREAD

**Issue by xianyu-123** [jiujiezz/deephlapan#41]
在使用setup.py安装之后，使用推荐的单肽段检测方法，会出现如下的问题，这个问题应该怎么解决呢？
(wanggj) wanggj@kemove-System-Product-Name:~$ deephlapan -P LNIMNKLNI -H HLA-A02:01 
Traceback (most recent call last):
  File "/home/wanggj/.conda/envs/wanggj/bin/deephlapan", line 4, in <module>
    __import__('pkg_resources').run_script('deephlapan==1.1', 'deephlapan')
  File "/home/wanggj/.conda/envs/wanggj/lib/python3.7/site-packages/pkg_resources/__init__.py", line 662, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/wanggj/.conda/envs/wanggj/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1459, in run_script
    exec(code, namespace, namespace)
  File "/home/wanggj/.conda/envs/wanggj/lib/python3.7/site-packages/deephlapan-1.1-py3.7.egg/EGG-INFO/scripts/deephlapan", line 3, in <module>
    from deephlapan.deephlapan_main import *
  File "/home/wanggj/.conda/envs/wanggj/lib/python3.7/site-packages/deephlapan-1.1-py3.7.egg/deephlapan/deephlapan_main.py", line 13, in <module>
    from attention import Attention
ModuleNotFoundError: No module named 'attention'

如果直接使用deephlapan_main.py， 不会报任何错误但也不会有任何输出？
感谢您的回复

**Comment by wujingcheng** [comment]
安装的时候有报错吗
